[pytest]
addopts = --html=reports/report.html --self-contained-html
markers =
    login: Login page tests
    inventory: Inventory page tests
    cart: Cart page tests
    checkout: Checkout flow tests
    sorting: Sorting functionality tests
